# Generated by Django 5.2.6 on 2026-03-29 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_sync_accepted_answer_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='accepted_answer',
        ),
    ]
