# Generated by Django 5.2.6 on 2026-05-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_accepted_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_bad',
            field=models.BooleanField(default=False),
        ),
    ]
