# Generated by Django 5.2.6 on 2026-05-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_answer_is_bad'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, help_text='Пользовательский титул', max_length=100),
        ),
    ]
