# Generated by Django 5.2.6 on 2026-05-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
