# Generated by Django 5.2.6 on 2026-05-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chosen_title',
            field=models.CharField(blank=True, help_text='Выбранный титул из ранее полученных', max_length=100, null=True),
        ),
    ]
